const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function deployAndWait(factory, ...args) {
  const contract = await factory.deploy(...args);
  await contract.waitForDeployment();
  await sleep(1500);
  return contract;
}

async function main() {
  console.log("Deploying all ARKIVE contracts to Base Sepolia...\n");

  const PointsSystem = await hre.ethers.getContractFactory("PointsSystem");
  const pointsSystem = await deployAndWait(PointsSystem);
  const pointsAddr = await pointsSystem.getAddress();
  console.log("PointsSystem:  ", pointsAddr);

  const WalletLinker = await hre.ethers.getContractFactory("WalletLinker");
  const walletLinker = await deployAndWait(WalletLinker);
  const linkerAddr = await walletLinker.getAddress();
  console.log("WalletLinker:  ", linkerAddr);

  const UserRegistry = await hre.ethers.getContractFactory("UserRegistry");
  const userRegistry = await deployAndWait(UserRegistry);
  const userAddr = await userRegistry.getAddress();
  console.log("UserRegistry:  ", userAddr);
  await userRegistry.setWalletLinker(linkerAddr);
  await sleep(1500);
  console.log("  WalletLinker set on UserRegistry");

  const PostRegistry = await hre.ethers.getContractFactory("PostRegistry");
  const postRegistry = await deployAndWait(PostRegistry, pointsAddr, linkerAddr);
  const postAddr = await postRegistry.getAddress();
  console.log("PostRegistry:  ", postAddr);

  const VaultRegistry = await hre.ethers.getContractFactory("VaultRegistry");
  const vaultRegistry = await deployAndWait(VaultRegistry, linkerAddr);
  const vaultAddr = await vaultRegistry.getAddress();
  console.log("VaultRegistry: ", vaultAddr);

  await pointsSystem.setWalletLinker(linkerAddr);
  await sleep(1500);
  console.log("\nWalletLinker set on PointsSystem");

  await pointsSystem.authoriseCaller(postAddr);
  await sleep(1500);
  console.log("PostRegistry authorised to award points");

  console.log("\nLocking contract config (irreversible)…");
  await userRegistry.lockConfig();
  await sleep(1500);
  await postRegistry.lockConfig();
  await sleep(1500);
  await vaultRegistry.lockConfig();
  await sleep(1500);
  await pointsSystem.lockConfig();
  console.log("Config locked on all registries");

  const addresses = {
    PointsSystem: pointsAddr,
    WalletLinker: linkerAddr,
    UserRegistry: userAddr,
    PostRegistry: postAddr,
    VaultRegistry: vaultAddr,
    deployedAt: new Date().toISOString(),
    network: "baseSepolia",
    chainId: 84532,
  };

  const configPath = path.join(__dirname, "../../frontend/src/config/contracts.js");
  fs.writeFileSync(
    configPath,
    `// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};
`,
  );
  console.log("\nAddresses saved to frontend/src/config/contracts.js");

  const names = ["PointsSystem", "WalletLinker", "UserRegistry", "PostRegistry", "VaultRegistry"];
  for (const name of names) {
    const artifact = await hre.artifacts.readArtifact(name);
    const abiPath = path.join(__dirname, `../../frontend/src/contracts/${name}.json`);
    fs.writeFileSync(abiPath, JSON.stringify({ abi: artifact.abi }, null, 2));
  }
  console.log("ABIs copied to frontend/src/contracts/\n");
  console.log("=== DEPLOYMENT COMPLETE ===");
  console.log(JSON.stringify(addresses, null, 2));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
