// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESSES = {
  "PointsSystem": "0x62712B6855f14Ef4b849BA539a948a6163c7d20C",
  "WalletLinker": "0x9f431Ee6b124A3B0Ffc3D8564CF539B90Ec2Cd1C",
  "UserRegistry": "0xB2a65F13f7b0C0ad194089908009A05bf8FDc942",
  "PostRegistry": "0xe05d4054c4050e8D53474C06D034a685b09f8A55",
  "VaultRegistry": "0xe3ee4509f8da48f33E43EaC9d8F7bb05E8024589",
  "deployedAt": "2026-07-01T02:13:53.066Z",
  "network": "baseSepolia",
  "chainId": 84532
};
